翻译改动
maikebing/codemaid pull request #3
Opened 2018-04-07 16:01 UTC by heku

你好，做了以下发动，请review/merge
-  Cleanup 统一翻译成“清理”（原先我看你有的地方是“清理”，有的地方又是“整理”）
-  Spade/Digging相关的翻译（码锹，发掘等）统一翻译成了“代码视图”
-  将“Reorgnizing"相关的翻译（重新组织）统一翻译成了”整理“ 
-  补充翻译了VS”Extensions and Updates“界面的内容

有任何问题欢迎讨论（不过明天开始上班了，不一定能及时回复）

2018-04-07 17:45 UTC, maikebing commented
- Cleanup

   我本来计划是翻译为整理的， 因为我觉得整理更贴切一点， 但是清理， 也应该没问题。

- Spade/Digging

  我觉得翻译为 “代码视图” 依然欠妥， 就功能而言， 这个视图可以 显示出 元数据 和 复杂度 ，可以删除 和查找引用。

2018-04-07 17:46 UTC, maikebing commented
- Reorgnizing

重新组织和整顿的意思， 整理我觉得很贴切， 那就确定  Cleanup 是 清理   Reorgnizing  是整理。

2018-04-07 17:53 UTC, maikebing requested changes
source.extension.vsixmanifest  文件VS本身就支持资源文件， 不必要这么做。

2018-04-07 17:54 UTC, maikebing requested changes
我觉得翻译为 “代码视图” 依然欠妥， 就功能而言， 这个视图可以 显示出 元数据 和 复杂度 ，可以删除 和查找引用。

2018-04-07 17:54 UTC, maikebing approved these changes

2018-04-08 02:51 UTC, heku commented
> source.extension.vsixmanifest 文件VS本身就支持资源文件， 不必要这么做。

source.extension.xx.resx文件只是ExtensibilityTools根据source.extension.vsixmanifest生成的，但它并不是本地化source.extension.vsixmanifest里面内容的，它只本地化VS | Help | About Microsoft Visual Studio菜单里显示的内容。而VS | Tools | Extensions and Updates里的显示内容是根据source.extension.vsixmanifest文件来的。本地化这块内容参考[localizing-vsix-packages](https://docs.microsoft.com/en-us/visualstudio/extensibility/localizing-vsix-packages)

>我觉得翻译为 “代码视图” 依然欠妥， 就功能而言， 这个视图可以 显示出 元数据 和 复杂度 ，可以删除 和查找引用。

Spade的功能和点点类似VS自己的Document Outline，我觉得当初不是起了叫“Spade”这个特殊的名字，从功能上讲或许叫Code Outline更合适，所以我建议我们将这个工具窗口翻译成“CodeMaid 代码视图”，或者“CodeMaid 代码大纲视图”，或者“CodeMaid 大纲视图”，你觉得呢？

2018-04-08 03:01 UTC, maikebing commented
Spade  这个词 我也一直犹豫很久， 原文里面 用 Spade 这个词 可能就像 CodeMaid  一样倾向于 昵称，而不是按照工具。所以我倾向于保持原味， 直译是“铁锹”， 它是处理和优化代码的铁锹 ，所以简称 “ 码锹 ”！或者 就跟 CodeMaid 一样， 直接保持原文。

2018-04-08 03:01 UTC, maikebing approved these changes

2018-04-08 04:32 UTC, heku commented
Spade确实不好翻译，直接字面翻译过来的“铁锹，码锹”感觉有点让人不知所云。我怀疑Spade这个词在当地是不是有其他意思（俚语），要不我问问作者为什么选择这个词，是不是就是铁锹的意思，还是有其他什么意思。

2018-04-08 04:35 UTC, maikebing commented
你问问吧， 该怎么翻译，怎么理解，  如果是有什么其他俚语 什么的， 那我们也可以考虑一下。 就像  “码云” 其实是git托管服务， 我们也可以用类似的“码锹”（需要继续斟酌）的名字。

2018-04-08 04:45 UTC, heku commented
我问了，开源中国的“码云”这个名字其实把我雷到了，哈哈。

2018-04-08 12:59 UTC, heku commented
我刚又更新了一点
- 统一将Region以关键字#region的方式显示
>关于 region
msdn中
#region请参见
C# 预处理器指令
#region 使您得以在使用 Visual Studio 代码编辑器的大纲显示功能时指定可展开或折叠的代码块。

MSDN中这句话好像不是说region=大纲，只是说在右键菜单的“大纲显示”相关功能中，可对这些region标识的代码块进行展开或折叠，所以region应该是指代码块。但我觉得这类关键字还是保留原样比较好，不会有歧义，每个程序员一看都明白，我也注意了下中文VS设置界面里的一些菜单，region也是以关键字#region的原文出现的。

- 将Attribute翻译成“特性”，以免和Property混淆
- 暂将Spade/Digging统一翻译成“代码大纲”（待后面进一步讨论确认）

2018-04-08 16:05 UTC, heku commented
又核对了一晚上，修改了不少的地方，主要从以下几点进行修改的：
- 有些翻译不统一，将它们统一（如联结行，联接行，排序行，多行排序，格式化注释，格式注释...等等）
- 有些中文翻译在VS中有对应的菜单，就是直接用VS菜单里的名字（如 对 Using 进行删除和排序）
- 从语义上对一些句子进行调整，让表达更易理解
- 修正若干错误的地方

请你有时间的时候review下，有任何疑问我们再讨论讨论。
另外发现还有不少地方没有翻译（代码中的一些message，一些tooltip内容等），看来还得搞段时间啊。。。

2018-04-08 16:08 UTC, maikebing commented
好的 。 正在看。

2018-04-09 14:33 UTC, heku commented
我这边中文环境发现一个奇怪的问题，只有第一次打开时CodeMaid会显示中文菜单，重新打开VS时就变成英文菜单了，你那边有没有这种情况？（我试了VS2017和VS2015都有这个问题）

2018-04-09 16:21 UTC, maikebing commented
我没太注意到这个问题

2018-04-10 00:53 UTC, heku commented
那我晚上把spade/digging的部分改回来吧，其他地方你有什么问题没？

2018-04-10 02:10 UTC, maikebing commented
其他没有问题

2018-04-10 15:45 UTC, heku commented
我将‘码锹’改名为‘码锹窗口’（和‘生成进度’对齐）同时做了些修改让本地化能正确显示。

2018-04-10 16:26 UTC, maikebing approved these changes

2018-04-10 16:26 UTC, maikebing commented on CodeMaid/CodeMaid.zh-Hans.vsct
> +          <CommandName>CodeMaid码锹窗口</CommandName>
工具栏。 这里是。

2018-04-10 16:26 UTC, merged

2018-04-12 14:37 UTC, heku commented on CodeMaid/CodeMaid.zh-Hans.vsct
> +          <CommandName>CodeMaid码锹窗口</CommandName>
这处我是和其他地方保持一致的名字，所以没有100%按英文来翻译

2018-04-12 14:39 UTC, heku commented
兄弟，代码里面还有一些message你还打算翻译吗？

2018-04-13 04:03 UTC, maikebing commented
我这几天找到了一些，已经提交，你可以看下
针对诊断信息我没有进行翻译， 觉得没必要。 
你看看还有没有遗漏的。